site_name: SQLDelight
site_url: https://cashapp.github.io/sqldelight/
repo_name: sqldelight
repo_url: https://github.com/cashapp/sqldelight
site_description: "SQLDelight - Generates typesafe Kotlin APIs from SQL"
site_author: Square, Inc.
copyright: 'Copyright &copy; 2019 Square, Inc.'
remote_branch: gh-pages

nav:
  - 'Overview': index.md
  - 'Changelog': changelog.md
  - 'Contributing': contributing.md
  - 'Code of Conduct': code_of_conduct.md

  - 'Android':
    - 'Getting Started': android_sqlite/index.md
    - 'SQL':
      - 'Projections': android_sqlite/custom_projections.md
      - 'Arguments': android_sqlite/query_arguments.md
      - 'Types': android_sqlite/types.md
      - 'Transactions': android_sqlite/transactions.md
    - 'Extensions':
        - 'RxJava': android_sqlite/rxjava.md
        - 'Coroutines': android_sqlite/coroutines.md
        - 'Android Paging': android_sqlite/android_paging.md
    - 'Migrations': android_sqlite/migrations.md
    - 'Testing': android_sqlite/testing.md
    - 'IntelliJ Plugin': android_sqlite/intellij_plugin.md
    - 'Gradle': android_sqlite/gradle.md
    - 'Upgrading Pre-1.0': android_sqlite/upgrading.md
    - '1.x API':
        - 'coroutines-extensions': /1.x/coroutines-extensions/index.html
        - 'rxjava2-extensions': /1.x/rxjava2-extensions/index.html
        - 'rxjava3-extensions': /1.x/rxjava3-extensions/index.html
        - 'android-paging': /1.x/android-paging/index.html
        - 'android-driver': /1.x/android-driver/index.html
        - 'runtime': /1.x/runtime/index.html
    - 'Resources': android_sqlite/resources.md


  - 'Multiplatform':
      - 'Getting Started': multiplatform_sqlite/index.md
      - 'SQL':
          - 'Projections': multiplatform_sqlite/custom_projections.md
          - 'Arguments': multiplatform_sqlite/query_arguments.md
          - 'Types': multiplatform_sqlite/types.md
          - 'Transactions': multiplatform_sqlite/transactions.md
      - 'Extensions':
          - 'Coroutines': multiplatform_sqlite/coroutines.md
      - 'Migrations': multiplatform_sqlite/migrations.md
      - 'IntelliJ Plugin': multiplatform_sqlite/intellij_plugin.md
      - 'Gradle': multiplatform_sqlite/gradle.md
      - 'Resources': multiplatform_sqlite/resources.md
      - '1.x API':
          - 'coroutines-extensions': /1.x/coroutines-extensions/index.html
          - 'runtime': /1.x/runtime/index.html

  - 'MySQL (JVM)':
      - 'Getting Started': jvm_mysql/index.md
      - 'SQL':
          - 'Projections': jvm_mysql/custom_projections.md
          - 'Arguments': jvm_mysql/query_arguments.md
          - 'Types': jvm_mysql/types.md
          - 'Transactions': jvm_mysql/transactions.md
      - 'Migrations': jvm_mysql/migrations.md
      - 'IntelliJ Plugin': jvm_mysql/intellij_plugin.md
      - 'Gradle': jvm_mysql/gradle.md
      - '1.x API':
          - 'jdbc-driver': /1.x/jdbc-driver/index.html
          - 'runtime': /1.x/runtime/index.html

  - 'PostgreSQL (JVM)':
      - 'Getting Started': jvm_postgresql/index.md
      - 'SQL':
          - 'Projections': jvm_postgresql/custom_projections.md
          - 'Arguments': jvm_postgresql/query_arguments.md
          - 'Types': jvm_postgresql/types.md
          - 'Transactions': jvm_postgresql/transactions.md
      - 'Migrations': jvm_postgresql/migrations.md
      - 'IntelliJ Plugin': jvm_postgresql/intellij_plugin.md
      - 'Gradle': jvm_postgresql/gradle.md
      - '1.x API':
          - 'jdbc-driver': /1.x/jdbc-driver/index.html
          - 'runtime': /1.x/runtime/index.html

  - 'HSQL (JVM)':
      - 'Getting Started': jvm_h2/index.md
      - 'SQL':
          - 'Projections': jvm_h2/custom_projections.md
          - 'Arguments': jvm_h2/query_arguments.md
          - 'Types': jvm_h2/types.md
          - 'Transactions': jvm_h2/transactions.md
      - 'Migrations': jvm_h2/migrations.md
      - 'IntelliJ Plugin': jvm_h2/intellij_plugin.md
      - 'Gradle': jvm_h2/gradle.md
      - '1.x API':
          - 'jdbc-driver': /1.x/jdbc-driver/index.html
          - 'runtime': /1.x/runtime/index.html

  - 'SQLite (Native)':
    - 'Getting Started': native_sqlite/index.md
    - 'SQL':
        - 'Projections': native_sqlite/custom_projections.md
        - 'Arguments': native_sqlite/query_arguments.md
        - 'Types': native_sqlite/types.md
        - 'Transactions': native_sqlite/transactions.md
    - 'Extensions':
        - 'Coroutines': native_sqlite/coroutines.md
    - 'Migrations': native_sqlite/migrations.md
    - 'IntelliJ Plugin': native_sqlite/intellij_plugin.md
    - 'Gradle': native_sqlite/gradle.md
    - '1.x API':
      - 'coroutines-extensions': /1.x/coroutines-extensions/index.html
      - 'native-driver': /1.x/native-driver/index.html
      - 'runtime': /1.x/runtime/index.html

  - 'SQLite (JVM)':
    - 'Getting Started': jvm_sqlite/index.md
    - 'SQL':
        - 'Projections': jvm_sqlite/custom_projections.md
        - 'Arguments': jvm_sqlite/query_arguments.md
        - 'Types': jvm_sqlite/types.md
        - 'Transactions': jvm_sqlite/transactions.md
    - 'Extensions':
        - 'RxJava': jvm_sqlite/rxjava.md
        - 'Coroutines': jvm_sqlite/coroutines.md
    - 'Migrations': jvm_sqlite/migrations.md
    - 'IntelliJ Plugin': jvm_sqlite/intellij_plugin.md
    - 'Gradle': jvm_sqlite/gradle.md
    - '1.x API':
        - 'coroutines-extensions': /1.x/coroutines-extensions/index.html
        - 'rxjava2-extensions': /1.x/rxjava2-extensions/index.html
        - 'rxjava3-extensions': /1.x/rxjava3-extensions/index.html
        - 'sqlite-driver': /1.x/sqlite-driver/index.html
        - 'runtime': /1.x/runtime/index.html

  - '1.x API':
      - 'android-driver': 1.x/android-driver/index.md
      - 'android-paging': 1.x/android-paging/index.md
      - 'coroutines-extensions': 1.x/coroutines-extensions/index.md
      - 'jdbc-driver': 1.x/jdbc-driver/index.md
      - 'native-driver': 1.x/native-driver/index.md
      - 'runtime': 1.x/runtime/index.md
      - 'rxjava2-extensions': 1.x/rxjava2-extensions/index.md
      - 'rxjava3-extensions': 1.x/rxjava3-extensions/index.md
      - 'sqlite-driver': 1.x/sqlite-driver/index.md
      - 'Internal':
        - 'sqldelight-compiler': 1.x/sqldelight-compiler/index.md
        - 'sqldelight-gradle-plugin': 1.x/sqldelight-gradle-plugin/index.md
        - 'sqlite-migrations': 1.x/sqlite-migrations/index.md

theme:
  name: 'material'
  favicon: images/icon-cashapp.png
  logo: images/icon-cashapp.png
  palette:
    primary: 'deep purple'
    accent: 'pink'
  feature:
    tabs: true

extra_css:
  - 'css/app.css'

markdown_extensions:
  - codehilite:
      guess_lang: false

plugins:
  - search
  - macros

extra:
  versions:
    sqldelight: '1.3.0'
